version: '3'
services:

  server1:
    image: ws-server
    environment:
      - APP_PORT=8080
      - APP_ID=001
    depends_on:
      - redis

  server2:
    image: ws-server
    environment:
      - APP_PORT=8080
      - APP_ID=002
    depends_on:
      - redis

  server3:
    image: ws-server
    environment:
      - APP_PORT=8080
      - APP_ID=003
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379

  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - server1
      - server2
      - server3
